#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 7.4
#  in conjunction with Tcl version 8.6
#    Jul 14, 2022 03:00:58 PM CST  platform: Windows NT

import sys
import tkinter as tk
import tkinter.ttk as ttk
from tkinter.constants import *

import interfaz_support
from AnalizadorLexico import *
from analizadorSintactico import *

class Toplevel1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = 'gray40' # X11 color: #666666
        _ana1color = '#c3c3c3' # Closest X11 color: 'gray76'
        _ana2color = 'beige' # X11 color: #f5f5dc
        _tabfg1 = 'black' 
        _tabfg2 = 'black' 
        _tabbg1 = 'grey75' 
        _tabbg2 = 'grey89' 
        _bgmode = 'light' 

        top.geometry("701x621+291+121")
        top.minsize(120, 1)
        top.maxsize(1284, 701)
        top.resizable(1,  1)
        top.title("Toplevel 0")
        top.configure(background="#004080")

        self.top = top





        self.Frame1 = tk.Frame(self.top)
        self.Frame1.place(relx=0.0, rely=0.089, relheight=0.919, relwidth=1.009)
        self.Frame1.configure(relief='groove')
        self.Frame1.configure(borderwidth="2")
        self.Frame1.configure(relief="groove")
        self.Frame1.configure(background="#004080")
        def lexico():
            datos=self.codigo.get(1.0, tk.END+"-1c")
            mostrarLex(datos)

        self.lexico = tk.Button(self.Frame1)
        self.lexico.place(relx=0.184, rely=0.893, height=34, width=154)
        self.lexico.configure(activebackground="beige")
        self.lexico.configure(activeforeground="#000000")
        self.lexico.configure(background="#000000")
        self.lexico.configure(compound='left')
        self.lexico.configure(disabledforeground="#a3a3a3")
        self.lexico.configure(font="-family {Segoe UI} -size 10 -weight bold")
        self.lexico.configure(foreground="#ffffff")
        self.lexico.configure(highlightbackground="#d9d9d9")
        self.lexico.configure(command=lexico)
        self.lexico.configure(highlightcolor="black")
        self.lexico.configure(pady="0")
        self.lexico.configure(text='''Analizador Lexico''')

        def sint():
            datos = self.codigo.get(1.0, tk.END + "-1c")
            mostrarSintc(datos)



        self.sintactico = tk.Button(self.Frame1)
        self.sintactico.place(relx=0.608, rely=0.893, height=34, width=157)
        self.sintactico.configure(activebackground="beige")
        self.sintactico.configure(activeforeground="#000000")
        self.sintactico.configure(background="#000000")
        self.sintactico.configure(compound='left')
        self.sintactico.configure(disabledforeground="#a3a3a3")
        self.sintactico.configure(font="-family {Segoe UI} -size 10 -weight bold")
        self.sintactico.configure(foreground="#ffffff")
        self.sintactico.configure(highlightbackground="#d9d9d9")
        self.sintactico.configure(highlightcolor="black")
        self.sintactico.configure(command=sint)
        self.sintactico.configure(pady="0")
        self.sintactico.configure(text='''Analizador sintactico''')

        self.codigo = tk.Text(self.Frame1)
        self.codigo.place(relx=0.017, rely=0.019, relheight=0.841, relwidth=0.965)
        self.codigo.configure(background="#808080")
        self.codigo.configure(font="-family {Segoe UI} -size 10 -weight bold")
        self.codigo.configure(foreground="#080808")
        self.codigo.configure(highlightbackground="#d9d9d9")
        self.codigo.configure(highlightcolor="black")
        self.codigo.configure(insertbackground="black")
        self.codigo.configure(selectbackground="#c4c4c4")
        self.codigo.configure(selectforeground="black")
        self.codigo.configure(wrap="word")

        self.Label1 = tk.Label(self.top)
        self.Label1.place(relx=-0.017, rely=0.0, height=57, width=717)
        self.Label1.configure(anchor='w')
        self.Label1.configure(background="#000000")
        self.Label1.configure(compound='left')
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(font="-family {Segoe UI} -size 20 -weight bold")
        self.Label1.configure(foreground="#ffffff")
        self.Label1.configure(padx="200")
        self.Label1.configure(text='''Analizador lexico-sintactico''')



def start_up():
    interfaz_support.main()

if __name__ == '__main__':
    interfaz_support.main()




